### ISSUE TITLE
paths.testSupport['js'] could be a hash not a string

### ISSUE THREAD

**Issue by jschilli** [sir-dunxalot/ember-cli-concat#8]
running ember test in my project produces:
```
TypeError: Object #<Object> has no method 'replace'
  at cleanPath (/Users/jschilli/dev/extern/ember-cli-concat/index.js:51:15)
  at Class.module.exports.postprocessTree (/Users/jschilli/dev/extern/ember-cli-concat/index.js:335:29)
  at /Users/jschilli/dev/myApp/node_modules/ember-cli/lib/broccoli/ember-app.js:318:27
  at Array.forEach (native)
  at EmberApp.addonPostprocessTree (/Users/jschilli/dev/myApp/node_modules/ember-cli/lib/broccoli/ember-app.js:316:23)
  at EmberApp.appAndDependencies (/Users/jschilli/dev/myApp/node_modules/ember-cli/lib/broccoli/ember-app.js:766:31)
```

the value of paths.testSupport['js'] is:
```
{ testSupport: '/assets/test-support.js',
  testLoader: '/assets/test-loader.js' }
```

I suspect this is an ordering issue - e.g. when ember-cli-concat runs relative to the rest of the plugins (which  unless `before` or `after` is specified in the plugins is alphabetical.

Given that any plugin can push assets into testSupport I think we should handle this like app assets 

I'll work up a PR for this

**Comment by jschilli** [comment]
@sir-dunxalot probably worth updating the ember-cli version on this as well to get current for testing purposes
